"use client";

import { Download, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import { AreaChart, ConnectionNotice, MetricCard, PageIntro } from "@/components/dashboard-primitives";
import { channelMetrics, trendData } from "@/lib/data";
import { formatCompactCurrency } from "@/lib/metrics";

export function AnalyticsDashboard() {
  const [range, setRange] = useState("30d");
  return <div className="page-grid"><PageIntro title="Acquisition intelligence" description="Understand what earns attention, what converts, and where revenue begins. Demonstration data uses a provider-neutral schema." actions={<button className="ghost-button" type="button"><Download className="size-3.5" />Export report</button>} /><ConnectionNotice module="Analytics" />
    <div className="metric-grid"><MetricCard label="Sessions" value="284.6K" change="+18.2%" detail="236.1K previous" tone="cyan" /><MetricCard label="Conversion rate" value="4.38%" change="+0.6%" detail="Blended conversion" tone="lime" /><MetricCard label="Cost per lead" value="$18.42" change="-7.2%" detail="Efficiency improving" tone="yellow" /><MetricCard label="Revenue" value="$128.4K" change="+24.1%" detail="Attributed estimate" tone="pink" /></div>
    <section className="panel"><div className="panel-header"><div><h3 className="section-title">Performance curve</h3><p className="section-description">Qualified traffic compared with conversion volume.</p></div><div className="flex gap-2"><div className="segmented">{["7d","30d","90d"].map((item) => <button key={item} data-active={range===item} onClick={() => setRange(item)}>{item.toUpperCase()}</button>)}</div><button className="icon-control" aria-label="Filter analytics"><SlidersHorizontal className="size-4" /></button></div></div><div className="panel-body"><AreaChart data={range === "7d" ? trendData.slice(-7) : trendData} primaryLabel="Qualified sessions" secondaryLabel="Conversions" /></div></section>
    <div className="content-grid-2"><section className="panel"><div className="panel-header"><div><h3 className="section-title">Channel contribution</h3><p className="section-description">Acquisition sources ordered by visitor volume.</p></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Channel</th><th>Visitors</th><th>Leads</th><th>CVR</th><th>Revenue</th><th>Trend</th></tr></thead><tbody>{channelMetrics.map((row) => <tr key={row.channel}><td className="font-medium">{row.channel}</td><td>{row.visitors.toLocaleString()}</td><td>{row.leads}</td><td>{row.conversion}%</td><td>{formatCompactCurrency(row.revenue)}</td><td className={row.trend>=0?"text-secondary":"text-destructive"}>{row.trend>=0?"+":""}{row.trend}%</td></tr>)}</tbody></table></div></section>
      <section className="panel"><div className="panel-header"><div><h3 className="section-title">Conversion funnel</h3><p className="section-description">From first session to attributed customer.</p></div></div><div className="space-y-5 p-5">{[{label:"Sessions",value:"284,550",width:"100%",color:"var(--chart-3)"},{label:"Engaged",value:"164,820",width:"73%",color:"var(--chart-2)"},{label:"Leads",value:"12,464",width:"47%",color:"var(--chart-5)"},{label:"Customers",value:"1,248",width:"24%",color:"var(--chart-1)"}].map((item,index)=><div key={item.label}><div className="mb-2 flex justify-between text-xs"><span>{index+1}. {item.label}</span><strong>{item.value}</strong></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full" style={{width:item.width,background:item.color}} /></div></div>)}</div></section></div>
  </div>;
}
