"use client";

import { useState } from "react";
import { BarChart3, Check, ContactRound, MailOpen, Plug, RotateCw } from "lucide-react";
import { PageIntro } from "@/components/dashboard-primitives";
import { connectionCards } from "@/lib/data";

const icons={analytics:BarChart3,crm:ContactRound,newsletter:MailOpen};
export function ConnectionsDashboard(){const [configured,setConfigured]=useState<string[]>([]);return <div className="page-grid"><PageIntro title="Connection center" description="Attach one provider to each operating module. Provider names stay intentionally open until you choose the tools."/><div className="grid gap-4 xl:grid-cols-3">{connectionCards.map((connection)=>{const Icon=icons[connection.id as keyof typeof icons];const active=configured.includes(connection.id);return <article className="panel overflow-hidden" key={connection.id}><div className="h-1 bg-[var(--connection-color)]" style={{"--connection-color":`var(--chart-${connection.color==="cyan"?3:connection.color==="lime"?2:5})`} as React.CSSProperties}/><div className="p-5"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-muted"><Icon className="size-5"/></span><span className={`status-badge ${active?"border-chart-2/35 bg-chart-2/10 text-chart-2":"border-border text-muted-foreground"}`}><span className={`status-dot ${active?"bg-chart-2":"bg-muted-foreground"}`}/>{active?"Configured":"Not connected"}</span></div><h3 className="mt-6 text-base font-semibold">{connection.name}</h3><p className="mt-2 min-h-12 text-xs leading-5 text-muted-foreground">{connection.description}</p><div className="mt-5 flex flex-wrap gap-1.5">{connection.fields.map((field)=><span key={field} className="rounded-md bg-muted/50 px-2 py-1 font-mono text-[9px] text-muted-foreground">{field}</span>)}</div><button className={active?"ghost-button mt-6 w-full":"action-button mt-6 w-full"} type="button" onClick={()=>setConfigured((current)=>active?current.filter((id)=>id!==connection.id):[...current,connection.id])}>{active?<><RotateCw className="size-3.5"/>Reset demo</>:<><Plug className="size-3.5"/>Configure</>}</button>{active?<p className="mt-3 flex items-center gap-2 text-[10px] text-secondary"><Check className="size-3"/>Adapter surface prepared. No external call made.</p>:null}</div></article>})}</div><section className="panel"><div className="panel-header"><div><h3 className="section-title">How connections flow</h3><p className="section-description">The UI stays stable while provider adapters normalize external data.</p></div></div><div className="grid gap-px bg-border/60 md:grid-cols-4">{["Provider API","Credential boundary","Normalized adapter","Marketing OS module"].map((step,index)=><div className="bg-card p-5" key={step}><span className="font-mono text-[10px] text-primary">0{index+1}</span><p className="mt-5 text-sm font-medium">{step}</p><p className="mt-2 text-[10px] leading-4 text-muted-foreground">{index===0?"Your selected analytics, CRM, or email platform.":index===1?"Secrets remain server-side and scoped to one connector.":index===2?"Provider fields map into stable internal types.":"Pages render one consistent operational model."}</p></div>)}</div></section></div>}
