"use client";

import { useMemo, useState } from "react";
import { Download, Mail, MessageSquarePlus, Search, SlidersHorizontal, UserPlus, X } from "lucide-react";
import { ConnectionNotice, MetricCard, PageIntro } from "@/components/dashboard-primitives";
import { contacts as initialContacts, pipeline, type CrmContact } from "@/lib/data";
import { filterContacts, formatCompactCurrency } from "@/lib/metrics";

const stageTone: Record<CrmContact["stage"], string> = { New: "border-chart-3/35 bg-chart-3/10 text-chart-3", Qualified: "border-chart-2/35 bg-chart-2/10 text-chart-2", Proposal: "border-chart-5/35 bg-chart-5/10 text-chart-5", Won: "border-chart-1/35 bg-chart-1/10 text-chart-1" };

export function CrmDashboard() {
  const [query,setQuery]=useState(""); const [stage,setStage]=useState("All"); const [contacts,setContacts]=useState(initialContacts); const [selected,setSelected]=useState<CrmContact|null>(null); const [notice,setNotice]=useState("");
  const visible=useMemo(()=>filterContacts(contacts,query,stage),[contacts,query,stage]);
  const updateStage=(value:CrmContact["stage"])=>{if(!selected)return;setContacts((current)=>current.map((item)=>item.id===selected.id?{...item,stage:value}:item));setSelected({...selected,stage:value});setNotice(`Moved to ${value}. Demo data only.`)};
  return <div className="page-grid"><PageIntro title="Relationship pipeline" description="Move from attention to conversation with every contact, signal, and next action in one operating view." actions={<div className="flex gap-2"><button className="ghost-button" type="button"><Download className="size-3.5"/>Export</button><button className="action-button" type="button"><UserPlus className="size-3.5"/>Add contact</button></div>}/><ConnectionNotice module="CRM"/>
    <div className="metric-grid"><MetricCard label="Pipeline value" value="$1.19M" change="+16.4%" detail="527 opportunities" tone="pink"/><MetricCard label="Qualified" value="148" change="+12.6%" detail="28 need action" tone="lime"/><MetricCard label="Win rate" value="22.7%" change="+3.1%" detail="Last 90 days" tone="cyan"/><MetricCard label="Avg. cycle" value="19d" change="-2.4d" detail="First touch to win" tone="yellow"/></div>
    <section className="panel"><div className="panel-header"><div><h3 className="section-title">Pipeline shape</h3><p className="section-description">Opportunity count and current value by stage.</p></div></div><div className="grid gap-px bg-border/60 sm:grid-cols-2 xl:grid-cols-4">{pipeline.map((item)=><article key={item.stage} className="bg-card p-4"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-muted-foreground">{item.stage}</span><span className="status-dot" style={{background:item.color}}/></div><strong className="mt-5 block text-3xl">{item.count}</strong><span className="mt-1 block font-mono text-[10px] text-muted-foreground">{formatCompactCurrency(item.value)} value</span></article>)}</div></section>
    <section className="panel"><div className="panel-header"><div><h3 className="section-title">People and opportunities</h3><p className="section-description">Select a contact to inspect context and next steps.</p></div><div className="flex flex-wrap gap-2"><label className="relative"><Search className="absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground"/><input className="filter-input pl-9" aria-label="Search contacts" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search contacts"/></label><label className="relative"><SlidersHorizontal className="pointer-events-none absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground"/><select className="select-control pl-9" aria-label="Filter by stage" value={stage} onChange={(event)=>setStage(event.target.value)}>{["All","New","Qualified","Proposal","Won"].map((value)=><option key={value}>{value}</option>)}</select></label></div></div><div className="data-table-wrap">{visible.length?<table className="data-table"><thead><tr><th>Contact</th><th>Company</th><th>Stage</th><th>Source</th><th>Owner</th><th>Value</th><th>Last touch</th></tr></thead><tbody>{visible.map((contact)=><tr key={contact.id} onClick={()=>{setSelected(contact);setNotice("")}} className="cursor-pointer"><td><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-muted font-mono text-[10px]">{contact.avatar}</span><div><p className="font-medium">{contact.name}</p><p className="text-[10px] text-muted-foreground">{contact.email}</p></div></div></td><td>{contact.company}</td><td><span className={`status-badge ${stageTone[contact.stage]}`}>{contact.stage}</span></td><td>{contact.source}</td><td>{contact.owner}</td><td className="font-mono">{formatCompactCurrency(contact.value)}</td><td className="text-muted-foreground">{contact.lastTouch}</td></tr>)}</tbody></table>:<div className="empty-state"><div><p className="font-medium text-foreground">No contacts match these filters.</p><button type="button" className="mt-3 text-xs text-primary underline" onClick={()=>{setQuery("");setStage("All")}}>Reset filters</button></div></div>}</div></section>
    {selected?<div className="drawer-backdrop" onMouseDown={(event)=>{if(event.currentTarget===event.target)setSelected(null)}}><aside className="detail-drawer" role="dialog" aria-modal="true" aria-labelledby="contact-name"><div className="drawer-header"><div className="flex gap-3"><span className="grid size-11 place-items-center rounded-xl bg-primary text-sm font-semibold text-primary-foreground">{selected.avatar}</span><div><p className="page-eyebrow">Contact record</p><h2 id="contact-name" className="mt-1 font-semibold">{selected.name}</h2><p className="text-xs text-muted-foreground">{selected.role} · {selected.company}</p></div></div><button className="icon-control" onClick={()=>setSelected(null)} aria-label="Close contact details" autoFocus><X className="size-4"/></button></div><div className="drawer-body"><div className="grid grid-cols-2 gap-3"><div className="rounded-lg border border-border p-3"><span className="page-eyebrow">Opportunity</span><strong className="mt-2 block text-xl">{formatCompactCurrency(selected.value)}</strong></div><div className="rounded-lg border border-border p-3"><span className="page-eyebrow">Last touch</span><strong className="mt-2 block text-sm">{selected.lastTouch}</strong></div></div><div><label className="page-eyebrow" htmlFor="contact-stage">Pipeline stage</label><select id="contact-stage" className="select-control mt-2 w-full" value={selected.stage} onChange={(event)=>updateStage(event.target.value as CrmContact["stage"])}>{["New","Qualified","Proposal","Won"].map((value)=><option key={value}>{value}</option>)}</select></div><div><p className="page-eyebrow">Contact</p><a className="mt-2 flex items-center gap-2 text-xs text-accent" href={`mailto:${selected.email}`}><Mail className="size-3.5"/>{selected.email}</a></div><div><label className="page-eyebrow" htmlFor="contact-note">Add a note</label><textarea id="contact-note" className="mt-2 min-h-28 w-full rounded-lg border border-border bg-background/60 p-3 text-xs outline-none focus:border-primary" placeholder="Capture context for the next touch…"/></div>{notice?<p className="rounded-lg bg-secondary/10 p-3 text-xs text-secondary">{notice}</p>:null}</div><div className="drawer-footer"><button className="action-button w-full" type="button" onClick={()=>setNotice("Note saved locally. Connect your CRM to sync it.")}><MessageSquarePlus className="size-3.5"/>Save demo note</button></div></aside></div>:null}
  </div>;
}
