"use client";

import { useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, Clock3, MailPlus, Send, Sparkles, X } from "lucide-react";
import { AreaChart, ConnectionNotice, MetricCard, PageIntro } from "@/components/dashboard-primitives";
import { campaigns, trendData } from "@/lib/data";
import { filterCampaigns } from "@/lib/metrics";

const statusTone:Record<string,string>={Sent:"border-chart-2/35 bg-chart-2/10 text-chart-2",Scheduled:"border-chart-5/35 bg-chart-5/10 text-chart-5",Draft:"border-chart-3/35 bg-chart-3/10 text-chart-3"};

export function NewsletterDashboard(){
  const [status,setStatus]=useState("All"); const [composer,setComposer]=useState(false); const [message,setMessage]=useState("");
  const visible=useMemo(()=>filterCampaigns(campaigns,status),[status]);
  return <div className="page-grid"><PageIntro title="Newsletter operations" description="Plan, publish, and learn from every send while keeping audience health visible." actions={<button className="action-button" type="button" onClick={()=>setComposer(true)}><MailPlus className="size-3.5"/>New campaign</button>}/><ConnectionNotice module="Newsletter"/>
    <div className="metric-grid"><MetricCard label="Subscribers" value="38,492" change="+8.4%" detail="1,248 net new" tone="yellow"/><MetricCard label="Average open" value="48.6%" change="+4.2%" detail="Last 10 sends" tone="pink"/><MetricCard label="Click rate" value="9.4%" change="+1.8%" detail="3.2K engaged" tone="cyan"/><MetricCard label="List health" value="97.8" change="+0.7" detail="Strong deliverability" tone="lime"/></div>
    <div className="content-grid-2"><section className="panel"><div className="panel-header"><div><h3 className="section-title">Audience growth</h3><p className="section-description">Subscribers and engaged readers across the last 30 days.</p></div><span className="demo-chip"><span className="status-dot bg-secondary"/>Healthy</span></div><div className="panel-body"><AreaChart data={trendData.map((point)=>({...point,primary:Math.min(100,point.primary+8),secondary:Math.max(8,point.secondary-8)}))} primaryLabel="Subscribers" secondaryLabel="Engaged"/></div></section><section className="panel"><div className="panel-header"><div><h3 className="section-title">List health</h3><p className="section-description">Deliverability signals from recent sends.</p></div></div><div className="space-y-4 p-5">{[{label:"Delivered",value:"99.3%",width:"99%",tone:"var(--chart-2)"},{label:"Engaged in 90 days",value:"72.8%",width:"73%",tone:"var(--chart-3)"},{label:"Bounce rate",value:"0.4%",width:"8%",tone:"var(--chart-5)"},{label:"Unsubscribe rate",value:"0.12%",width:"4%",tone:"var(--chart-1)"}].map((item)=><div key={item.label}><div className="mb-2 flex justify-between text-xs"><span>{item.label}</span><strong>{item.value}</strong></div><div className="h-1.5 rounded-full bg-muted"><div className="h-full rounded-full" style={{width:item.width,background:item.tone}}/></div></div>)}</div></section></div>
    <section className="panel"><div className="panel-header"><div><h3 className="section-title">Campaigns</h3><p className="section-description">Drafts, scheduled sends, and recent performance.</p></div><div className="segmented">{["All","Draft","Scheduled","Sent"].map((item)=><button key={item} data-active={status===item} onClick={()=>setStatus(item)}>{item}</button>)}</div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Campaign</th><th>Status</th><th>Audience</th><th>Send</th><th>Open</th><th>Click</th></tr></thead><tbody>{visible.map((campaign)=><tr key={campaign.id}><td><p className="font-medium">{campaign.name}</p><p className="mt-1 text-[10px] text-muted-foreground">{campaign.subject}</p></td><td><span className={`status-badge ${statusTone[campaign.status]}`}>{campaign.status}</span></td><td>{campaign.audience}</td><td className="text-muted-foreground">{campaign.sentAt}</td><td className="font-mono">{campaign.openRate?`${campaign.openRate}%`:"—"}</td><td className="font-mono">{campaign.clickRate?`${campaign.clickRate}%`:"—"}</td></tr>)}</tbody></table></div></section>
    <div className="content-grid-equal"><section className="panel"><div className="panel-header"><div><h3 className="section-title">Active sequences</h3><p className="section-description">Automated journeys ready for a future provider.</p></div></div><div className="divide-y divide-border/60">{[{name:"New subscriber welcome",step:"3 messages",icon:Sparkles,tone:"text-chart-1"},{name:"Event attendee follow-up",step:"2 messages",icon:Send,tone:"text-chart-3"},{name:"Quiet reader re-engagement",step:"4 messages",icon:Clock3,tone:"text-chart-5"}].map((item)=><div className="flex items-center gap-3 p-4" key={item.name}><span className={`grid size-8 place-items-center rounded-lg bg-muted ${item.tone}`}><item.icon className="size-4"/></span><div className="flex-1"><p className="text-xs font-medium">{item.name}</p><p className="text-[10px] text-muted-foreground">{item.step} · Draft logic</p></div><ArrowRight className="size-4 text-muted-foreground"/></div>)}</div></section><section className="panel"><div className="panel-header"><div><h3 className="section-title">Operational checklist</h3><p className="section-description">Pre-send safeguards built into the workflow.</p></div></div><div className="space-y-3 p-5">{["Audience and suppression rules reviewed","Links and tracking parameters checked","Desktop and mobile preview approved","Sender domain health confirmed"].map((item)=><div className="flex items-center gap-3 text-xs" key={item}><CheckCircle2 className="size-4 text-secondary"/><span>{item}</span></div>)}</div></section></div>
    {composer?<div className="drawer-backdrop items-center justify-center p-4" onMouseDown={(event)=>{if(event.currentTarget===event.target)setComposer(false)}}><section className="w-full max-w-xl rounded-xl border border-border bg-card shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="composer-title"><div className="drawer-header"><div><p className="page-eyebrow">Campaign composer</p><h2 id="composer-title" className="mt-1 text-lg font-semibold">Start a new send</h2></div><button className="icon-control" onClick={()=>setComposer(false)} aria-label="Close campaign composer" autoFocus><X className="size-4"/></button></div><form className="space-y-4 p-5" onSubmit={(event)=>{event.preventDefault();setMessage("Draft created locally. Connect your newsletter tool to sync it.")}}><label className="grid gap-2 text-xs">Campaign name<input required className="filter-input" placeholder="e.g. Sunday Field Notes #43"/></label><label className="grid gap-2 text-xs">Subject line<input required className="filter-input" placeholder="Write a clear promise"/></label><label className="grid gap-2 text-xs">Audience<select className="select-control"><option>Main list</option><option>Builders</option><option>Workshop cohort</option></select></label>{message?<p className="rounded-lg bg-secondary/10 p-3 text-xs text-secondary">{message}</p>:null}<button className="action-button w-full" type="submit">Create demo draft</button></form></section></div>:null}
  </div>;
}
