"use client";

import Link from "next/link";
import { ArrowRight, CircleAlert, Clock3, MailCheck, MoveUpRight, Plus, UsersRound } from "lucide-react";
import { useState } from "react";

import { AreaChart, MetricCard, PageIntro } from "@/components/dashboard-primitives";
import { campaigns, overviewMetrics, pipeline, trendData } from "@/lib/data";
import { formatCompactCurrency } from "@/lib/metrics";

export function OverviewDashboard() {
  const [period, setPeriod] = useState("30d");
  return <div className="page-grid"><PageIntro title="Your growth system, at a glance" description="A single operating view across acquisition, relationships, and audience. Figures are demonstration data until providers are connected." actions={<div className="flex items-center gap-2"><span className="demo-chip"><span className="status-dot bg-secondary" />Demo data</span><button className="action-button" type="button"><Plus className="size-3.5" />New campaign</button></div>} />
    <div className="metric-grid">{overviewMetrics.map((metric) => <MetricCard key={metric.label} {...metric} />)}</div>
    <div className="content-grid-2"><section className="panel"><div className="panel-header"><div><h3 className="section-title">Cross-channel momentum</h3><p className="section-description">Reach and conversion signal across the operating window.</p></div><div className="segmented" aria-label="Chart period">{["7d","30d","90d"].map((item) => <button type="button" data-active={period === item} onClick={() => setPeriod(item)} key={item}>{item.toUpperCase()}</button>)}</div></div><div className="panel-body"><AreaChart data={period === "7d" ? trendData.slice(-7) : trendData} /></div></section>
      <section className="panel"><div className="panel-header"><div><h3 className="section-title">Operating alerts</h3><p className="section-description">What needs your attention next.</p></div><span className="demo-chip">3 items</span></div><div className="divide-y divide-border/60"><div className="flex gap-3 p-4"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-chart-5/15 text-chart-5"><Clock3 className="size-4" /></span><div><p className="text-xs font-medium">Campaign ready for review</p><p className="mt-1 text-[10px] text-muted-foreground">Marketing OS preview · scheduled Aug 25</p></div></div><div className="flex gap-3 p-4"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-chart-1/15 text-chart-1"><CircleAlert className="size-4" /></span><div><p className="text-xs font-medium">14 qualified leads need follow-up</p><p className="mt-1 text-[10px] text-muted-foreground">Oldest untouched lead · 3 days</p></div></div><div className="flex gap-3 p-4"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-chart-2/15 text-chart-2"><MailCheck className="size-4" /></span><div><p className="text-xs font-medium">List health is strong</p><p className="mt-1 text-[10px] text-muted-foreground">Bounce rate below 0.4% this month</p></div></div></div></section></div>
    <div className="content-grid-equal"><section className="panel"><div className="panel-header"><div><h3 className="section-title">Pipeline snapshot</h3><p className="section-description">$1.19M across 527 active opportunities.</p></div><Link className="ghost-button" href="/crm">Open CRM <ArrowRight className="size-3" /></Link></div><div className="grid gap-3 p-4 sm:grid-cols-2">{pipeline.map((stage) => <div key={stage.stage} className="rounded-lg border border-border bg-background/40 p-3"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-muted-foreground">{stage.stage}</span><span className="status-dot" style={{background:stage.color}} /></div><div className="mt-4 flex items-end justify-between"><strong className="text-2xl">{stage.count}</strong><span className="font-mono text-[10px] text-muted-foreground">{formatCompactCurrency(stage.value)}</span></div></div>)}</div></section>
      <section className="panel"><div className="panel-header"><div><h3 className="section-title">Campaign pulse</h3><p className="section-description">Recent newsletter work and audience response.</p></div><Link className="ghost-button" href="/newsletter">Open studio <ArrowRight className="size-3" /></Link></div><div className="divide-y divide-border/60">{campaigns.slice(0,3).map((campaign) => <div key={campaign.id} className="flex items-center gap-3 p-4"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-primary/15 text-primary"><MailCheck className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{campaign.name}</p><p className="mt-1 truncate text-[10px] text-muted-foreground">{campaign.status} · {campaign.sentAt}</p></div><span className="font-mono text-xs">{campaign.openRate ? `${campaign.openRate}%` : "—"}</span></div>)}</div></section></div>
    <section className="panel"><div className="panel-header"><div><h3 className="section-title">Activity stream</h3><p className="section-description">The latest meaningful actions across every connected system.</p></div></div><div className="grid gap-px bg-border/60 md:grid-cols-3"><article className="bg-card p-4"><UsersRound className="size-4 text-chart-2" /><p className="mt-4 text-xs font-medium">Lead moved to Proposal</p><p className="mt-1 text-[10px] text-muted-foreground">Jon Bell · Atlas Ops · 18 min ago</p></article><article className="bg-card p-4"><MoveUpRight className="size-4 text-chart-3" /><p className="mt-4 text-xs font-medium">Organic traffic crossed 98K</p><p className="mt-1 text-[10px] text-muted-foreground">Analytics · 42 min ago</p></article><article className="bg-card p-4"><MailCheck className="size-4 text-chart-1" /><p className="mt-4 text-xs font-medium">Workshop follow-up reached 62.1%</p><p className="mt-1 text-[10px] text-muted-foreground">Newsletter · 2 hours ago</p></article></div></section>
  </div>;
}
